# Clone projects I need / am working on (TODO: better, not one each like that)
# Do not overwrite if already exists with local changes; that errors, so ignore.
- name: "Download devbox repo"
  git:
    repo: "git@github.com:waxmittmann/devbox.git"
    dest: "{{ workspace_dir }}/Projects/Useful/devbox"
    accept_hostkey: True
    force: no
  become: yes
  become_user: damxam
  ignore_errors: yes

- name: "Download github repos"
  git:
    repo: "git@github.com:waxmittmann/{{ item.path }}.git"
    dest: "{{ workspace_dir }}/Projects/{{ item.type }}/{{ item.name }}"
    accept_hostkey: True
    force: no
  become: yes
  become_user: damxam
  ignore_errors: yes
  with_items:
    - { path: 'neo4j-movies-java-bolt', type: 'Experimental', name: 'neo4j-movies-java-bolt' }
    - { path: 'workflowManagers', type: 'Experimental', name: 'workflowManagers' }

- name: "Download gitlab repos (private, so needs valid ssh key)"
  git:
    repo: "git@gitlab.com:damxam/{{ item.repo }}.git"
    dest: "{{ workspace_dir }}/Notes/{{ item.path }}"
    accept_hostkey: True
    force: no
  become: yes
  become_user: damxam
  ignore_errors: yes
  with_items:
    - { repo: Notes, path: VersionedNotes }
