---
- name: Install
  include_role:
    name: install_if_missing
  vars:
    install_dir: "{{ workspace_dir }}/IDEs"
    extract_dir: VSCode-linux-x64

    download_url: "https://vscode-update.azurewebsites.net/latest/linux-x64/stable"
    download_filename: "code-stable-code_1.21.1-1521038896_amd64.tar.gz"

    sym_link: {
      link_name: vscode,
      binary_path: "bin/code"
    }
