---

# Todo: This check should use installed_to_dir
- name: "Set installed_to_dir"
  block:
  - name: "If renaming extracted dir, use renamed name for final dir"
    set_fact:
      installed_to_dir: "{{ rename_to_dir }}"
    when: rename_to_dir is defined
  - name: "Else, use extracted-to directory"
    set_fact:
      installed_to_dir: "{{ extract_dir }}"
    when: rename_to_dir is not defined
- name: Check whether directory exists
  stat:
    path: "{{ install_dir }}/{{ installed_to_dir }}"
  register: installed
- name: Do download and install
  block:
  - name: Create dir
    file:
      path: "{{ install_dir }}"
      state: directory
      owner: damxam
      group: damxam
  - name: Download to dir
    get_url:
      url: "{{ download_url }}"
      dest: "{{ install_dir }}"
      owner: damxam
      group: damxam
  - name: Extract to dir
    unarchive:
      src: "{{ install_dir }}/{{ download_filename }}"
      dest: "{{ install_dir }}"
      remote_src: Yes
      owner: damxam
      group: damxam

  - name: "Optional: Rename the extracted dir"
    command: "mv {{ install_dir }}/{{ extract_dir }} {{ install_dir }}/{{ rename_to_dir }}"
    when: rename_to_dir is defined

  - name: "Optional: Create link in /usr/bin"
    file:
      src: "{{ install_dir }}/{{ installed_to_dir }}/{{ sym_link.binary_path }}"
      dest: "/usr/bin/{{ sym_link.link_name }}"
      state: link
      owner: damxam
      group: damxam
    when: sym_link is defined
  when: not installed.stat.exists
