---
- hosts: all

  pre_tasks:
    - name: Create Install dir where we'll store all our binaries
      file: path=/AnsibleInstall state=directory

  roles:
    - workspace
    - anaconda
    - aptinstalls
    - zsh
    - sshkey
    - intellij

  sudo: true

  tasks:
      # Set git stuff
    - name: "Set git user email"
      shell: git config --global user.email "damxam@gmail.com"
      become: yes
      become_user: damxam
    - name: "Set git user name"
      shell: git config --global user.name "Max Wittmann"
      become: yes
      become_user: damxam

    # Clone projects I need / am working on (TODO: better, not one each like that)
    - name: "Download devbox repo"
      git:
        repo: "https://github.com/waxmittmann/devbox.git"
        dest: "{{ lookup('env', 'HOME') }}/Workspaces/Projects/Useful/devbox"
        accept_hostkey: True
        force: Yes
      become: yes
      become_user: damxam
