---
- hosts: all

  pre_tasks:
    - name: Create Install dir where we'll store all our binaries
      file: path=/AnsibleInstall state=directory

  vars_files:
    - ./config.json

  sudo: true

  tasks:
    - debug:
        msg: "Workspace dir is: {{ workspace_dir }}"
