---
- hosts: all

  pre_tasks:
    - name: Create Install dir where we'll store all our binaries
      file: path=/AnsibleInstall state=directory

  roles:
    - workspace
    - aptinstalls
    - anaconda
    - zsh
    - sshkey
    - intellij

  sudo: true

  tasks:
      # Set git stuff
    - name: "Set git stuff"
      block:
      - name: "Set git user email"
        shell: git config --global user.email "damxam@gmail.com"
        become: yes
        become_user: damxam
      - name: "Set git user name"
        shell: git config --global user.name "Max Wittmann"
        become: yes
        become_user: damxam

    # Clone projects I need / am working on (TODO: better, not one each like that)
    # Do not overwrite if already exists with local changes; that errors, so ignore.
    - name: "Download devbox repo"
      git:
        repo: "https://github.com/waxmittmann/devbox.git"
        dest: "{{ lookup('env', 'HOME') }}/Workspaces/Projects/Useful/devbox"
        accept_hostkey: True
        force: no
      become: yes
      become_user: damxam
      ignore_errors: yes

    - name: "Download github repos"
      git:
        repo: "git@github.com:{{ item.path }}.git"
        dest: "{{ lookup('env', 'HOME') }}/Workspaces/Projects/{{ item.type }}/{{ item.name }}"
        accept_hostkey: True
        force: no
      become: yes
      become_user: damxam
      ignore_errors: yes
      with_items:
        - { path: 'waxmittmann/neo4j-movies-java-bolt', type: 'Useful', name: 'neo4j-movies-java-bolt' }

    - name: "Add user to vboxsf group (virtualbox-specific)"
      command: "adduser damxam vboxsf"

    - name: "Add user to docker group"
      command: "adduser damxam docker"
