---
# Add apt repos

- name: add atom path to repo
  apt_repository: repo='ppa:webupd8team/atom' state=present
- name: add java repo
  apt_repository: repo='ppa:webupd8team/java' state=present
- name: Add sbt repo, part 1
  shell: "echo \"deb https://dl.bintray.com/sbt/debian /\" | sudo tee -a /etc/apt/sources.list.d/sbt.list"
- name: Add sbt repo, part 2
  shell: "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823"
- name: update apt cache (AFTER adding repos)
  apt: update_cache=yes

  # Install java; needs some extra license reading work
- name: java 8 license, 1
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
- name: java 8 license, 2
  shell: echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
- name: install java 8
  apt: name=oracle-java8-installer state=present force=yes

# Install all the other things
- name: install qdirstat
  apt: name=qdirstat  state=present force=yes
- name: install atom
  apt: name=atom state=present force=yes
- name: install git
  apt: name=git state=present force=yes
- name: install gitk
  apt: name=gitk state=present force=yes
- name: install pip
  apt: name=python-pip state=present force=yes
- name: install terminator (console replacement)
  apt: name=terminator state=present force=yes
- name: install vagrant
  apt: name=vagrant state=present force=yes
- name: install zsh
  apt: name=zsh state=present force=yes
- name: install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  become_user: damxam
- name: install sbt
  apt: name=sbt state=present force=yes
- name: run sbt (to force actual install)
  shell: sbt sbtVersion
- name: install scala from .deb (do same for sbt)
  apt:
    deb: https://www.scala-lang.org/files/archive/scala-2.12.1.deb
    state: present
