---

# Add apt repos
- name: Add apt repos
  block:
  - name: add atom path to repo
    apt_repository: repo='ppa:webupd8team/atom' state=present
  - name: add java repo
    apt_repository: repo='ppa:webupd8team/java' state=present
  - name: Add sbt repo, part 1
    shell: "echo \"deb https://dl.bintray.com/sbt/debian /\" | sudo tee -a /etc/apt/sources.list.d/sbt.list"
  - name: Add sbt repo, part 2
    shell: "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823"
  - name: update apt cache (AFTER adding repos)
    apt: update_cache=yes

# Install java; needs some extra license reading work
- name: install java
  block:
  - name: java 8 license, 1
    shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  - name: java 8 license, 2
    shell: echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
  - name: install java 8
    apt: name=oracle-java8-installer state=present force=yes

- name: install things via apt
  apt:
    name: "{{ item }}"
    state: present
    force: yes
  with_items: [
    "atom",
    "git",
    "gitk",
    "python-pip",
    "terminator",
    "vagrant",
    "zsh",
    "sbt",
    "xclip"
  ]

# Todo: When this fails for something, will further items still be run?
- name: install optional things via apt
  apt:
    name: "{{ item }}"
    state: present
    force: yes
  with_items: [
    "qdirstat"
  ]
  ignore_errors: yes

- name: run sbt (to force actual install)
  shell: sbt sbtVersion

- name: Install scala
  block:
  - name: Check whether scala is installed
    stat:
      path: "/usr/bin/scala"
    register: scala_exists
  - name: install scala from .deb (do same for sbt)
    apt:
      deb: https://www.scala-lang.org/files/archive/scala-2.12.1.deb
      state: present
    when: not scala_exists.stat.exists
