---
#Create my standard directory structure; there's a role in creating the work
# space and then pulling all your projects.

- name: create Workspace and notes dirs
  file:
    path: "{{ lookup('env', 'HOME') }}/{{ item }}"
    state: directory
    owner: damxam
    group: damxam
    mode: 0775
  with_items: [
    "/Workspaces/",
    "/Workspaces/Notes/",
    "/Workspaces/IDEs",
    "/Workspaces/Misc",
    "/Workspaces/Tools",
    "/Workspaces/Tools/bin",
    "/Workspaces/Data",
    "/Workspaces/Libraries",
    "/Workspaces/Libraries/bin",
    "/Workspaces/Libraries/GoPath",
    "/Workspaces/Projects",
    "/Workspaces/Projects/Useful",
    "/Workspaces/Projects/Experimental",
    "/Workspaces/Projects/Learning"
  ]
