---
#Create my standard directory structure; there's a role in creating the work
# space and then pulling all your projects.

- name: create Workspace and notes dirs
  file:
    path: "{{ workspace_dir }}/{{ item }}"
    state: directory
    owner: damxam
    group: damxam
    mode: 0775
  with_items: [
    "",
    "Notes/",
    "IDEs",
    "Misc",
    "Tools",
    "Tools/bin",
    "Data",
    "Libraries",
    "Libraries/bin",
    "Projects",
    "Projects/Useful",
    "Projects/Experimental",
    "Projects/Learning"
  ]
