---
- name: Install
  include_role:
    name: install_if_missing
  vars:
    install_dir: "{{ lookup('env', 'HOME') }}/Workspaces/Tools"
    extract_dir: smartgit

    download_url: "https://www.syntevo.com/downloads/smartgit/smartgit-linux-17_1_5.tar.gz"
    download_filename: "smartgit-linux-17_1_5.tar.gz"

    sym_link: {
      link_name: smartgit,
      binary_path: "bin/smartgit.sh"
    }
