---

- name: Check whether google client exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/Workspaces/Tools/bin/gdrive-linux-x64"
  register: gdrive_installed
- name: Download and install
  block:
  - name: Create dir for IntelliJ
    file:
      path: "{{ lookup('env', 'HOME') }}/Workspaces/Tools/bin"
      state: directory
      owner: damxam
      group: damxam
  - name: Download
    get_url:
      url: https://docs.google.com/uc?id=0B3X9GlR6EmbnQ0FtZmJJUXEyRTA&export=download
      #url: https://doc-10-a0-docs.googleusercontent.com/docs/securesc/7mh5m8gd5sgrgfb1smldekpqcgt8dd2d/jp8crphh68vmjbnusvf2tga8n1qbjpb9/1520978400000/15876260727594163214/01450348049954871657/0B3X9GlR6EmbnQ0FtZmJJUXEyRTA?e=download
      dest: "{{ lookup('env', 'HOME') }}/Workspaces/Tools/bin"
      mode: 0755
      owner: damxam
      group: damxam
  when: not gdrive_installed.stat.exists
