---
# Download my zsh extensions; would be nicer to update if exists maybe.

- name: install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
- name: "Remove old customs if exists"
  file:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/customs.zsh"
    state: absent
- name: Copy my custom zsh stuff in
  copy:
    src: ./files/customs.zsh
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/customs.zsh"
    owner: damxam
    group: damxam
- name: "Set .oh-my.zsh to be owned by user"
  file:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
    recurse: Yes
    owner: damxam
    group: damxam
- name: "Set zsh to be default shell"
  user:
    name: damxam
    shell: /bin/zsh
