---
- name: Install virtualenv
  pip:
    name: virtualenv

- name: Install tensorflow
  pip:
    name: tensorflow
    virtualenv: "{{ workspace_dir }}/Libraries/tensorflow"
    virtualenv_site_packages: true
  become: yes
  become_user: damxam
