---


- name: 'Check version'
  include_role:
    name: check_success
  vars:
    role_to_check: "{{ role_to_run }}"

# Todo: Explode if greater
- block:
  - name: 'Compare version'
    set_fact:
      # Todo: in  < 2.5 version was version_compare
      # Note: do NOT use interpolators inside these conditions (ie don't do {{ success_version }})
      is_up_to_date: "{{ devbox.skip_if_success and success_version is version(devbox.version, '>=') }}"
  - debug:
      msg: "comparing {{success_version}} >= {{devbox.version}} = {{ is_up_to_date }}, skip_if_success: {{ devbox.skip_if_success }}"

- name: 'Run if needed'
  block:
  - debug:
      msg: "IfSuccess: Running role {{ role_to_run }}"
  - name: 'Run task'
    include_role:
      name: "{{ role_to_run }}"
    # static: no (hmm what does this do?)

  # Todo: Write failure (for debugging; maybe could also have 'run failure only' mode)
  - name: 'Write success'
    include_role:
      name: write_success
    vars:
      role_to_complete: "{{ role_to_run }}"
  when: not is_up_to_date

- name: 'Print if we didnt run it'
  debug:
    msg: 'IfSuccess: Skipping role {{ role_to_run }}'
  when: is_up_to_date
