aptinstall_items:
  [
    "atom",
    "git",
    "gitk",
    "python-pip",
    "terminator",
    "vagrant",
    "sbt",
    "xclip",
    "neo4j",
    "maven",
    "net-tools"
    "virtualbox",
    "snapd",
    "nodejs",
    "npm"
  ]
