settings:
  skip_if_success: true

install:
  workspace_dir: "{{ lookup('env', 'HOME') }}/Workspaces"
  role:
    anaconda: false
    repos: true
    intellij: true
    foxitreader: true
    tensorflow: false
    kafka: false
    kubernetes: false
    vs_code: false
    postman: true
    smartgit: true
    helm: true
    zsh: true
    git: true
    docker: true
    nautilus: false
    virtualbox: true
    pipinstalls: true
    orientdb: true
