---
# Install Anaconda (Python)
# TODO: Add the bin folder to path

- name: Check whether Anaconda exists
  stat:
    path: "{{ workspace_dir }}/Libraries/Anaconda"
  register: anaconda_installed
- name: Download Anaconda
  get_url:
    url: https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh
    dest: "/AnsibleInstall"
    owner: damxam
    group: damxam
    mode: 0755
  when: not anaconda_installed.stat.exists
- name: Install python pexpect (needed to install Anaconda)
  pip:
    name: pexpect
- name: Install Anaconda
  command: /AnsibleInstall/Anaconda3-5.0.1-Linux-x86_64.sh -b -p "{{ lookup('env', 'HOME') }}/Workspaces/Libraries/Anaconda"
  become: yes
  become_user: damxam
  when: not anaconda_installed.stat.exists
