---

- name: Check version file exists
  stat:
    path: "./{{ role_to_check }}.success"
  ignore_errors: true
  register: version_file_exists

# todo block
- name: Attempt to read version file
  set_fact:
    # success_version: {{ lookup('file', './etc/{{ role_to_check }}') }}
    success_version: "{{ lookup('file', './{{ role_to_check }}.success') }}"
  when: version_file_exists and version_file_exists.stat.exists
- name: "Or set version to -1 (so always fails)"
  set_fact:
    # success_version: {{ lookup('file', './etc/{{ role_to_check }}') }}
    success_version: "0"
  when: not version_file_exists.stat.exists

- name: Print version to stdout
  debug:
    msg: "{{ role_to_check }}: {{ success_version }}"
